language: php
php:
- '5.4'
- '7.0'
- '7.1'
before_script:
branches:
  only:
  - master
env:
  global:
    secure:
        - QEdqhH3q/rwzWRZTlm040LlBZwmjF61cmKTnOgzjysLQXm/rK+TcJdkcliQW3eLYdNfjwR2haWKblpWIvH6ONVWv3Sdpbd50Ec4XzMkdjkWd1PzPtLEvnaKckH63MR1qbVpjtH/bdttXhzN0j3vF6/WjfY0b+cpu7SIw+lzbccAI9vRKd7y9a7HZwKprISuWTIQSf1CcwTzVj3kclO28lMYaIlIz9QZf0qqbH7vXcq8aQQD6WcNVnw1fpD2NIrCIl26cNWS3E66H0OG0VNOOQlPkYB832Kep/iwZCIn8kyYaWrJoNLt6Y/GuPn+2xSLz9fLKLfWZhUQLWjcEwKIDQpn5ritrRw0msNk8hwxCm/1Pvv2/fWqLMIGTaBaatVlQhjf/B9seCgK7PP1t8dlbm+J/76H7Pes8jcROc5/T97zHvdxD9KkskcWLwnDxtrya9nwfhSOlC6b1J9W2IooeLhGot92KCvMYY6y0WRRUQi3Qz7SnMLgleGbx4Ki7wBAM9Ex1ujF3tqcA9j9OlIW88U93RgPLJcGdLQ/mYALxZmjA67PgIolmUZJWqobWnmE18D7DYPyToAMCBMEGWrmXgghXDKZLok1nSG74A25vrT0DWW1pWQMuS9M96sfzHQ+vab1IvEavnfV78T4m9bD65zlJ4BOuCSNBCe0F+3eRvi0=
        - Cbs6bqixPYX8j9PdpnJZejs6nN7C4ZMob9U+eBNgh6NkFXS0eOTyjb45tg2AxUWHQzVUeQPXIMXIbUAja89MbtICN/2dXJ22jb3TGp3SXVU8F1suL0u4JlZpt0iUkOdkjUZn8JqGk/S4Gde5Tk2HvhyuZxHAZDJkyonEGXouasD1208EQnF35dNnIM0JQVHd/fV3lAcWaVepA63XoVD34G9+NRTsAzD3V12h4swR4UoMiHhT5N2bYHlsLS+NYjSpwnN7OFs72OcAeKHvr0ngU1zP+uYUHZET4jUXngoy05ROzXXaHTeyuvb66EM9Crzj6iTp3zoK577n8bViay3PtYzyQT0FKpAlT2MXo6lNxxWRvwXESB2iUAvKpZDDaP17KBp/DtJwVKy6unR6JAjm2icVBCP+Av2ZnPNIL0zA/E/9YS7WkexfDpX2/VIiuZvJlmo50uu2RIzdzb0a0EVJ7Mp8xY99OEz3e5kYLMPejby8Hevxh3uCzk5c6dxE5ZjtWgORxw3KWeVVGjEWZZe6gl6WrnzzAlmmZ891XGh7cI5ZLNTvgo5NeqCaVZbeeGN/nd0RFP8PCtfCU9MZYuQm1n91CimgrhpypUB27hOqt0zDmYSRmE9WGxHOX0ILRzpgUIZdqrfqyaX4kbYNqwflBBdiTGhJS8gWFPwx/KBPDSA=
after_success:
- "./deploy.sh"
